name: Build

on:
  push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        sudo apt update
        sudo apt-get install -y libudev-dev libgl-dev
      # libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        conan config init
        mkdir -p build; cd build && conan install .. --build=missing  -s compiler.libcxx=libstdc++20 -c tools.system.package_manager:mode=install && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build  . -- -j 3

    # - name: Build project
    #   run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake && cmake --build build

    # - name: Launch build script
    #   run: ./setup.sh

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Launch build script
  #     run: ./setup.bat