name: Build

on:
  push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    # - name: Install Dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y cmake
    #     sudo apt-get install -y libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev
    #     sudo apt-get install -y autoconf libtool

    - uses: lukka/get-cmake@latest
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-multi-vcpkg'
        buildPreset: 'ninja-multi-vcpkg'
    # - name: Build project
    #   run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake && cmake --build build

    # - name: Launch build script
    #   run: ./setup.sh

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Launch build script
  #     run: ./setup.bat