# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install graphviz -y
          sudo apt install doxygen -y

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build documentation
        run: doxygen

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          github_token: ${{ inputs.github_token }}
          folder: docs/build/html
          message: "Update generated documentation"
          branch: gh-pages